org: nitit
app: aws-flask-python
service: aws-python-flask-api-project

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:092973695436:table/peopleGSI-2"

resources:
  Resources:
    PeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: peopleGSI-2
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S  # Assuming id is a string, adjust if needed
          - AttributeName: name
            AttributeType: S  # Assuming name is a string, adjust if needed
          - AttributeName: career
            AttributeType: S  # Assuming career is a string, adjust if needed
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
