name: Newman Run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm install
          npm install -g serverless
          npm install werkzeug

      - name: Run serverless wsgi serve
        run: serverless wsgi serve

      - name: Wait for serverless to start
        run: sleep 10  # Adjust the sleep duration based on your serverless startup time
        
      - name: Debug Files in Directory
        run: ls
  
      - name: Run Postman Tests
        uses: matt-ball/newman-action@master
        with:
          collection: CollectionCURD.json
          environment: EnviromentCURD.json
